<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php if($_video = $_product->getData('aw_video')):?>
<div class="product-image product-image-zoom">
	<a  data-toggle="modal" href="#zoomVideo"><?php echo $_video; ?></a>
    <div class="modal fade" id="zoomVideo">
		<?php echo $_video; ?>
    </div>
</div>
<?php endif;?>

<?php /*if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="product-image product-image-zoom">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
    ?>

		    <div class="modal fade" id="zoom<?php echo $_product->getId()?>">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">×</a>
                    <h3><?php echo $_product->getName()?></h3>
                </div>
			    <div class="modal-body">
			    	<?php //echo $this->getLayout()->createBlock('catalog/product_gallery')->setTemplate('catalog/product/gallery.phtml')->toHtml()?>
			    	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(600)?>" alt="<?php echo $this->htmlEscape($this->getImageLabel())?>" title="<?php echo $this->htmlEscape($this->getImageLabel())?>" />
			    </div>
			    <div class="modal-footer">
			    <a href="#" class="btn" data-dismiss="modal">Close</a>
			    </div>
		    </div>
            <a class="" data-toggle="modal" href="#zoom<?php echo $_product->getId()?>">
            	<?php echo $_helper->productAttribute($_product, $_img, 'image'); ?>
            </a>
</div>			            
<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; */?>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>

	<?php /*/ Video ?>
	<?php if($_video = $_product->getData('aw_video')):?>
		<a href="#zoomVideo" role="button" data-toggle="modal" ><?php echo $_video; ?></a>
	<?php endif;*/?>

	<?php // Images ?>
    <?php foreach ($this->getGalleryImages() as $_image): ?>

		<a href="#zoom<?php echo $_image->getId();?>" role="button" data-toggle="modal">
        	<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(100); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
		</a>

		<!-- Modal -->
		<div id="zoom<?php echo $_image->getId();?>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="zoom<?php echo $_image->getId();?>Label" aria-hidden="true">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		  </div>
		  <div class="modal-body">
        	<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(800,600); ?>" width="800" height="600" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
		  </div>
		</div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if($_additional = $this->getAdditionalData()): ?>
    <h2><?php echo $this->__('Additional Information') ?></h2>
    <table class="table table-striped table-bordered table-condensed" id="product-attribute-specs-table">
        <col class="span3" />
        <col class=""/>
        <tbody>
        <?php foreach ($_additional as $_data): ?>
            <tr>
                <th class=""><?php echo $this->htmlEscape($this->__($_data['label'])) ?></th>
                <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
<?php endif;?>


