<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="row-fluid">
	<?php echo $this->getChildHtml();?>
</div>
<div class="row-fluid">
	<div class="span12">
		<?php echo $this->getChildHtml('copyright');?>
	</div>
</div>
