<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php echo $this->getChildHtml(); /*?>
<div class="row-fluid">
	<div class="span4">
		<h5><?php echo $this->__('About us');?></h5>
		<?php echo $this->getChildHtml('about_us');?>
	</div>
	<div class="span4">
		<h5><?php echo $this->__('Your order');?></h5>
		<?php echo $this->getChildHtml('your_order');?>
	</div>
	<div class="span4">
		<h5><?php echo $this->__('Contact us');?></h5>
		<?php echo $this->getChildHtml('contact_us');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<?php echo $this->getChildHtml('copyright');?>
	</div>
</div>
<?php /*/?>
