<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<div class="nav-collapse">
	<ul class="nav">
	  <li><a class="brand" href="#">Nos autres sites:</a></li>
	  <li><a href="#Abcircle.fr" class="active">Abcircle.fr</a></li>
	  <li class="divider"></li>
	  <li><a href="#Bestoftv.fr">Bestoftv.fr</a></li>
	  <li><a href="#Shake-weight.fr">Shake-weight.fr</a></li>
	</ul>
    <?php echo $this->getChildHtml('topLinks') ?>
<?php /*?>
    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
<?php */?>
                
    <?php echo $this->getChildHtml('topSearch') ?>
</div><!--/.nav-collapse -->

<?php //echo $this->getChildHtml('topContainer'); ?>
<?php //echo $this->getChildHtml('topMenu') ?>
