<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="navbar navbar-fixed-top inverted">
    <div class="navbar-inner">
        <div class="container">

			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<div class="nav-collapse">

				<?php echo $this->getChildHtml('sponsorLinks') ?>
				<?php echo $this->getChildHtml('topLinks') ?>
			<?php /*?>
				<p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
			<?php */?>
						    
				<?php echo $this->getChildHtml('topSearch') ?>
			</div><!--/.nav-collapse -->

			<?php //echo $this->getChildHtml('topContainer'); ?>
			<?php //echo $this->getChildHtml('topMenu') ?>

        </div>
    </div>
</div>
<?php echo $this->getChildHtml('bannerslider') ?>

