<?php
	$bannerCollection = $this->getBannerCollection();
	$i = 0;
?>
<?php $timeDelay = $this->getDelayTime() ?>
<?php $showdesc = $this->isShowDescription() ?>
<?php $listStyle = $this->getListStyle() ?>
<?php $imagewidth = $this->getImageWidth() ?>
<?php $imageheight = $this->getImageHeight() ?>

<?php if (!count($bannerCollection)): ?>
<?php elseif ($listStyle == '1'):?>

<?php  $filter = new Mage_Widget_Model_Template_Filter(); ?>

<div id="carousel<?php echo $listStyle?>" class="carousel slide">
	<!-- Carousel items -->
	<div class="carousel-inner">
		<?php $i = 0; foreach ($bannerCollection as $banner): ?>
		<div class="item<?php echo @$i++>0?'':' active';?>">
			<div style="background: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>') no-repeat;height:450px;<?php //echo !@$imageheight?:'height:'.$imageheight.'px;'?>">
				<h1><a href="<?php echo $banner['weblink'];?>"><?php echo $banner['title']?></a></h1>				
				<?php if ($showdesc == '1'):?>
					<?php echo $filter->filter($banner['description']); ?>
				<?php endif;?>
			</div>
		</div>
		<?php endforeach; ?>
	</div>
	<!-- Shadow and navigation -->
	<p class="carousel-nav">
		<?php $i = 0; foreach ($bannerCollection as $banner): ?>
		<a data-target="myCarousel" data-to="<?php echo $i++;?>">&#9632;</a>
		<?php endforeach; ?>
	</p>
	<!-- Carousel nav -->
	<a class="carousel-control left ui-prev" href="#carousel<?php echo $listStyle?>" data-slide="prev"><i class=""></i></a>
	<a class="carousel-control right ui-next" href="#carousel<?php echo $listStyle?>" data-slide="next"><i class=""></i></a>
</div>
<?php endif;?>

