<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php //if ($this->helper('tax')->displayFullSummary() && $_value!=0): 
	$totalItems = Mage::getModel('checkout/cart')->getQuote()->getItemsCount();
	$totalQuantity = Mage::getModel('checkout/cart')->getQuote()->getItemsQty();

	$subTotal = Mage::getModel('checkout/cart')->getQuote()->getSubtotal();
	$grandTotal = Mage::getModel('checkout/cart')->getQuote()->getGrandTotal();
?>
    <div class="inverted nav bage bage-primary">
		<a href="<?php echo $this->getUrl('checkout/cart'); ?>"><i class="ui-shopping-cart"></i>
		<?php //$this->helper('tax')->displayFullSummary()?>
		<?php //echo $this->renderTotals(); ?>
		(<?php //echo $this->helper('core')->formatPrice($subTotal, false)?><?php echo $totalItems?>)
		</a>
    </div>
<?php //endif;?>




