<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>
<?php else: ?>
    <div class="nav bage bage-primary">
    	<img src="<?php echo $this->getSkinUrl('images/ui/shopping-cart.png')?>">
            <?php echo $this->renderTotals(); ?>
    </div>
<?php endif; ?>
