<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

?>

<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Radio */ ?>
<?php $_option = $this->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>

<script>
//<![CDATA[
typeof config				!== 'undefined' || (config				= <?php echo $this->getJsonConfig()?:'[]' ?>);
typeof config.options		!== 'undefined' || (config.options		= []);
typeof config.selected		!== 'undefined' || (config.selected		= []);
typeof config.selections	!== 'undefined' || (config.selections	= []);

<?php echo 'config.options['.$_option->getId().'] = '.$_option->toJson().";\n";?>
<?php
require_once "ChromePhp.php";
require_once "debug.php";
//console::log(get_class_info($_option));
//console::log(JSON_decode($_option->toJson()));
foreach( $_selections as $_selection){
	//console::log(get_class_info($_selection));
	echo 'config.selections['.$_selection->getId().'] = '.$_selection->toJson().";\n";
	if ($this->_isSelected($_selection)) echo 'config.selected['.$_option->getId().'] = true;';
}
?>
//]]>
</script>

<?php // for Product title ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<?php list($_defaultQty, $_canChangeQty) = $this->_getDefaultValues(); ?>

<label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label>
    <div class="input-box">
    <?php if ($this->_showSingle()): ?>
        <?php echo $this->getSelectionTitlePrice($_selections[0]) ?>
        <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>" />
    <?php else:?>
        <div class="controls">
        <?php if (!$_option->getRequired()): ?>
            <label class="radio" for="bundle-option-<?php echo $_option->getId() ?>"><?php echo $this->__('None') ?>
            	<input type="radio" onclick="bundle.changeSelection(this)" class="radio" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $_option->getId() ?>]"<?php echo ($_default && $_default->isSalable())?'':' checked="checked" ' ?> value=""/>
            </label>
        <?php endif; ?>
        <?php foreach ($_selections as $_selection): ?>
            <label class="btn-group radio <?php echo $_option->getRequired()?' required':''?>" for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>">
            	<div class="btn btn-big">
		        	<input type="radio" onclick="bundle.changeSelection(this)" <?php echo $_option->getRequired()?'required="required"':'' ?> id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>" name="bundle_option[<?php echo $_option->getId() ?>]"<?php if ($this->_isSelected($_selection)) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>value="<?php echo $_selection->getSelectionId() ?>"/>
            	</div>
            	<div class="btn btn-big">
		        	<?php if($_selection->getImage()):?>
		    		<img src="<?php echo $_selection->getThumbnailUrl(100); ?>" alt="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"/>
		        	<?php endif;?>
		        	<strong>
		        		<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
		        		<?php if($_section_price = $this->getSelectionPrice($_selection)):?>
						<span class="price-notice">+<span class="price"><?php echo Mage::getModel('directory/currency')->format($_section_price)?></span></span>
						<?php endif;?>
		        	</strong>
		    		<p><?php echo $_helper->productAttribute($_selection, $_selection->getName(), 'name') ?></p>
		        	<?php //echo $this->getSelectionTitlePrice($_selection) ?>
            	</div>
            </label>
            <?php if ($_option->getRequired()): ?>
                <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_selection->getSelectionId(), 'bundle-option-'.$_option->getId().'-container') ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
        <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
    <?php endif; ?>
    </div>
    <?php if ($_canChangeQty):?>
    <span class="qty-holder">
        <label for="bundle-option-<?php echo $_option->getId() ?>-qty-input"><?php echo $this->__('Qty:') ?>&nbsp;</label><input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>" type="text" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>"/>
    </span>
    <?php endif;?>
